packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - sharp
  - bcrypt
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild
  - msgpackr-extract
  - '@scarf/scarf'
  - '@nestjs/core'
