import type { BakeryCategory, BakerySize, CakeShape, CakeFlavor, CreamType } from './products.api';

export const CATEGORIES: { value: BakeryCategory; label: string; emoji: string; color: string }[] = [
  { value: 'CAKE', label: 'Cake', emoji: '🎂', color: 'pink' },
  { value: 'CUPCAKE', label: 'Cupcake', emoji: '🧁', color: 'pink' },
  { value: 'PASTRY', label: 'Pastry', emoji: '🥐', color: 'amber' },
  { value: 'BREAD', label: 'Bread', emoji: '🍞', color: 'amber' },
  { value: 'BUN', label: 'Bun', emoji: '🍔', color: 'amber' },
  { value: 'ROLL', label: 'Roll', emoji: '🥯', color: 'amber' },
  { value: 'BISCUIT', label: 'Biscuit', emoji: '🍪', color: 'orange' },
  { value: 'COOKIE', label: 'Cookie', emoji: '🍪', color: 'orange' },
  { value: 'DONUT', label: 'Donut', emoji: '🍩', color: 'pink' },
  { value: 'MUFFIN', label: 'Muffin', emoji: '🧁', color: 'orange' },
  { value: 'CROISSANT', label: 'Croissant', emoji: '🥐', color: 'amber' },
  { value: 'DANISH', label: 'Danish', emoji: '🥐', color: 'amber' },
  { value: 'PATTY', label: 'Patty', emoji: '🥟', color: 'orange' },
  { value: 'PUFF', label: 'Puff', emoji: '🥟', color: 'amber' },
  { value: 'PIZZA', label: 'Pizza', emoji: '🍕', color: 'red' },
  { value: 'SANDWICH', label: 'Sandwich', emoji: '🥪', color: 'amber' },
  { value: 'BURGER', label: 'Burger', emoji: '🍔', color: 'red' },
  { value: 'TART', label: 'Tart', emoji: '🥧', color: 'pink' },
  { value: 'PIE', label: 'Pie', emoji: '🥧', color: 'amber' },
  { value: 'CHEESECAKE', label: 'Cheesecake', emoji: '🍰', color: 'pink' },
  { value: 'DESSERT', label: 'Dessert', emoji: '🍨', color: 'pink' },
  { value: 'BROWNIE', label: 'Brownie', emoji: '🍫', color: 'amber' },
  { value: 'MACARON', label: 'Macaron', emoji: '🍬', color: 'pink' },
  { value: 'SWEETS', label: 'Sweets', emoji: '🍬', color: 'orange' },
  { value: 'BARFI', label: 'Barfi', emoji: '🍬', color: 'orange' },
  { value: 'LADDU', label: 'Laddu', emoji: '🟡', color: 'amber' },
  { value: 'GULAB_JAMUN', label: 'Gulab Jamun', emoji: '🟤', color: 'amber' },
  { value: 'RASMALAI', label: 'Rasmalai', emoji: '🥛', color: 'pink' },
  { value: 'KHEER', label: 'Kheer', emoji: '🥣', color: 'amber' },
  { value: 'CUSTOM_CAKE', label: 'Custom Cake', emoji: '🎂', color: 'fuchsia' },
  { value: 'WEDDING_CAKE', label: 'Wedding Cake', emoji: '💒', color: 'rose' },
  { value: 'BIRTHDAY_CAKE', label: 'Birthday Cake', emoji: '🎉', color: 'fuchsia' },
  { value: 'ANNIVERSARY_CAKE', label: 'Anniversary Cake', emoji: '💝', color: 'rose' },
  { value: 'BEVERAGE', label: 'Beverage', emoji: '🥤', color: 'cyan' },
  { value: 'ICE_CREAM', label: 'Ice Cream', emoji: '🍦', color: 'cyan' },
  { value: 'OTHER', label: 'Other', emoji: '⭐', color: 'slate' },
];

export const SIZES: { value: BakerySize; label: string; emoji: string; kg?: number; pound?: number }[] = [
  { value: 'MINI', label: 'Mini', emoji: '🎂' },
  { value: 'SMALL', label: 'Small', emoji: '🎂' },
  { value: 'MEDIUM', label: 'Medium', emoji: '🎂' },
  { value: 'LARGE', label: 'Large', emoji: '🎂' },
  { value: 'EXTRA_LARGE', label: 'Extra Large', emoji: '🎂' },
  { value: 'HALF_POUND', label: '½ Pound', emoji: '⚖️', pound: 0.5, kg: 0.227 },
  { value: 'ONE_POUND', label: '1 Pound', emoji: '⚖️', pound: 1, kg: 0.453 },
  { value: 'ONE_HALF_POUND', label: '1½ Pound', emoji: '⚖️', pound: 1.5, kg: 0.68 },
  { value: 'TWO_POUND', label: '2 Pound', emoji: '⚖️', pound: 2, kg: 0.907 },
  { value: 'THREE_POUND', label: '3 Pound', emoji: '⚖️', pound: 3, kg: 1.36 },
  { value: 'FIVE_POUND', label: '5 Pound', emoji: '⚖️', pound: 5, kg: 2.27 },
  { value: 'HALF_KG', label: '½ Kg', emoji: '⚖️', kg: 0.5 },
  { value: 'ONE_KG', label: '1 Kg', emoji: '⚖️', kg: 1 },
  { value: 'ONE_HALF_KG', label: '1½ Kg', emoji: '⚖️', kg: 1.5 },
  { value: 'TWO_KG', label: '2 Kg', emoji: '⚖️', kg: 2 },
  { value: 'THREE_KG', label: '3 Kg', emoji: '⚖️', kg: 3 },
  { value: 'FIVE_KG', label: '5 Kg', emoji: '⚖️', kg: 5 },
  { value: 'TEN_KG', label: '10 Kg', emoji: '⚖️', kg: 10 },
  { value: 'SLICE', label: 'Slice', emoji: '🍰' },
  { value: 'DOZEN', label: 'Dozen', emoji: '📦' },
  { value: 'HALF_DOZEN', label: '½ Dozen', emoji: '📦' },
  { value: 'TRAY', label: 'Tray', emoji: '🍱' },
  { value: 'BOX', label: 'Box', emoji: '📦' },
  { value: 'CUSTOM', label: 'Custom', emoji: '⚙️' },
];

export const SHAPES: { value: CakeShape; label: string; emoji: string }[] = [
  { value: 'ROUND', label: 'Round', emoji: '⭕' },
  { value: 'SQUARE', label: 'Square', emoji: '⬛' },
  { value: 'RECTANGLE', label: 'Rectangle', emoji: '▬' },
  { value: 'HEART', label: 'Heart', emoji: '❤️' },
  { value: 'OVAL', label: 'Oval', emoji: '⬭' },
  { value: 'TIER_2', label: '2-Tier', emoji: '🎂' },
  { value: 'TIER_3', label: '3-Tier', emoji: '🏛️' },
  { value: 'TIER_4', label: '4-Tier', emoji: '🏛️' },
  { value: 'TIER_5', label: '5-Tier', emoji: '🏛️' },
  { value: 'NUMBER', label: 'Number', emoji: '🔢' },
  { value: 'LETTER', label: 'Letter', emoji: '🔤' },
  { value: 'CHARACTER', label: 'Character', emoji: '🦄' },
  { value: 'CUSTOM_SHAPE', label: 'Custom', emoji: '✨' },
];

export const FLAVORS: { value: CakeFlavor; label: string; emoji: string; color: string }[] = [
  { value: 'VANILLA', label: 'Vanilla', emoji: '🤍', color: 'from-amber-100 to-amber-200' },
  { value: 'CHOCOLATE', label: 'Chocolate', emoji: '🍫', color: 'from-amber-800 to-amber-900' },
  { value: 'STRAWBERRY', label: 'Strawberry', emoji: '🍓', color: 'from-pink-400 to-rose-500' },
  { value: 'BLACK_FOREST', label: 'Black Forest', emoji: '🍒', color: 'from-red-900 to-rose-950' },
  { value: 'RED_VELVET', label: 'Red Velvet', emoji: '❤️', color: 'from-red-500 to-red-700' },
  { value: 'PINEAPPLE', label: 'Pineapple', emoji: '🍍', color: 'from-yellow-300 to-amber-400' },
  { value: 'MANGO', label: 'Mango', emoji: '🥭', color: 'from-orange-400 to-yellow-500' },
  { value: 'BUTTERSCOTCH', label: 'Butterscotch', emoji: '🍯', color: 'from-amber-400 to-orange-500' },
  { value: 'COFFEE', label: 'Coffee', emoji: '☕', color: 'from-amber-800 to-stone-800' },
  { value: 'CARAMEL', label: 'Caramel', emoji: '🍮', color: 'from-amber-500 to-orange-600' },
  { value: 'BLUEBERRY', label: 'Blueberry', emoji: '🫐', color: 'from-blue-500 to-indigo-600' },
  { value: 'RASPBERRY', label: 'Raspberry', emoji: '🫐', color: 'from-pink-500 to-rose-600' },
  { value: 'LEMON', label: 'Lemon', emoji: '🍋', color: 'from-yellow-300 to-lime-400' },
  { value: 'ORANGE', label: 'Orange', emoji: '🍊', color: 'from-orange-400 to-orange-500' },
  { value: 'BANANA', label: 'Banana', emoji: '🍌', color: 'from-yellow-200 to-yellow-400' },
  { value: 'CARROT', label: 'Carrot', emoji: '🥕', color: 'from-orange-400 to-orange-600' },
  { value: 'FRUIT', label: 'Fruit', emoji: '🍇', color: 'from-purple-400 to-pink-500' },
  { value: 'TIRAMISU', label: 'Tiramisu', emoji: '☕', color: 'from-stone-500 to-amber-700' },
  { value: 'OREO', label: 'Oreo', emoji: '⚫', color: 'from-slate-800 to-slate-900' },
  { value: 'KITKAT', label: 'KitKat', emoji: '🍫', color: 'from-red-600 to-red-800' },
  { value: 'FERRERO_ROCHER', label: 'Ferrero', emoji: '🌰', color: 'from-amber-700 to-yellow-800' },
  { value: 'NUTELLA', label: 'Nutella', emoji: '🍫', color: 'from-amber-900 to-stone-900' },
  { value: 'CHEESECAKE', label: 'Cheesecake', emoji: '🍰', color: 'from-yellow-100 to-amber-200' },
  { value: 'ICE_CREAM', label: 'Ice Cream', emoji: '🍦', color: 'from-blue-200 to-pink-300' },
  { value: 'MIXED', label: 'Mixed', emoji: '🌈', color: 'from-pink-400 via-yellow-400 to-blue-400' },
  { value: 'CUSTOM_FLAVOR', label: 'Custom', emoji: '✨', color: 'from-fuchsia-500 to-violet-600' },
];

export const CREAMS: { value: CreamType; label: string; emoji: string }[] = [
  { value: 'BUTTERCREAM', label: 'Buttercream', emoji: '🧈' },
  { value: 'WHIPPED_CREAM', label: 'Whipped Cream', emoji: '☁️' },
  { value: 'FRESH_CREAM', label: 'Fresh Cream', emoji: '🥛' },
  { value: 'GANACHE', label: 'Ganache', emoji: '🍫' },
  { value: 'FONDANT', label: 'Fondant', emoji: '✨' },
  { value: 'CREAM_CHEESE', label: 'Cream Cheese', emoji: '🧀' },
  { value: 'ROYAL_ICING', label: 'Royal Icing', emoji: '👑' },
  { value: 'MERINGUE', label: 'Meringue', emoji: '☁️' },
  { value: 'MOUSSE', label: 'Mousse', emoji: '🫧' },
  { value: 'MIRROR_GLAZE', label: 'Mirror Glaze', emoji: '💎' },
  { value: 'OTHER', label: 'Other', emoji: '⭐' },
];

export const OCCASIONS = [
  { value: 'BIRTHDAY', label: 'Birthday', emoji: '🎉' },
  { value: 'WEDDING', label: 'Wedding', emoji: '💒' },
  { value: 'ANNIVERSARY', label: 'Anniversary', emoji: '💝' },
  { value: 'ENGAGEMENT', label: 'Engagement', emoji: '💍' },
  { value: 'BABY_SHOWER', label: 'Baby Shower', emoji: '👶' },
  { value: 'GRADUATION', label: 'Graduation', emoji: '🎓' },
  { value: 'FAREWELL', label: 'Farewell', emoji: '👋' },
  { value: 'CORPORATE', label: 'Corporate', emoji: '💼' },
  { value: 'MEHNDI', label: 'Mehndi', emoji: '🎨' },
  { value: 'AQEEQA', label: 'Aqeeqa', emoji: '👶' },
  { value: 'EID', label: 'Eid', emoji: '🌙' },
  { value: 'CHRISTMAS', label: 'Christmas', emoji: '🎄' },
  { value: 'NEW_YEAR', label: 'New Year', emoji: '🎊' },
  { value: 'VALENTINES', label: "Valentine's", emoji: '💕' },
  { value: 'MOTHERS_DAY', label: "Mother's Day", emoji: '👩' },
  { value: 'FATHERS_DAY', label: "Father's Day", emoji: '👨' },
  { value: 'PROMOTION', label: 'Promotion', emoji: '🏆' },
  { value: 'HOUSEWARMING', label: 'Housewarming', emoji: '🏡' },
  { value: 'OTHER', label: 'Other', emoji: '⭐' },
];

export const CATEGORY_EMOJI: Record<string, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.value, c.emoji]),
);

export const OCCASION_EMOJI: Record<string, string> = Object.fromEntries(
  OCCASIONS.map((o) => [o.value, o.emoji]),
);
