/*
  Warnings:

  - You are about to drop the column `loyaltyEnabled` on the `TenantSettings` table. All the data in the column will be lost.
  - You are about to drop the column `loyaltyMinRedeem` on the `TenantSettings` table. All the data in the column will be lost.
  - You are about to drop the column `loyaltyPointsPerPKR` on the `TenantSettings` table. All the data in the column will be lost.
  - You are about to drop the column `loyaltyRedeemRate` on the `TenantSettings` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "TenantSettings" DROP COLUMN "loyaltyEnabled",
DROP COLUMN "loyaltyMinRedeem",
DROP COLUMN "loyaltyPointsPerPKR",
DROP COLUMN "loyaltyRedeemRate",
ADD COLUMN     "allowCredit" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowDiscount" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowNegativeStock" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoCreateCustomer" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoLogoutMinutes" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "autoPrintReceipt" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoReorder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "bannerUrl" TEXT,
ADD COLUMN     "brandColor" TEXT NOT NULL DEFAULT '#16a34a',
ADD COLUMN     "businessType" TEXT,
ADD COLUMN     "closeTime" TEXT,
ADD COLUMN     "compactMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "confirmBeforeCheckout" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "creditOverdueDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'PKR',
ADD COLUMN     "currencySymbol" TEXT NOT NULL DEFAULT 'Rs',
ADD COLUMN     "dailySummaryTime" TEXT NOT NULL DEFAULT '21:00',
ADD COLUMN     "dateFormat" TEXT NOT NULL DEFAULT 'DD/MM/YYYY',
ADD COLUMN     "defaultCreditLimit" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "defaultLowStockAlert" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "defaultMarkup" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "defaultPaymentMethod" TEXT NOT NULL DEFAULT 'CASH',
ADD COLUMN     "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableBarcodeScanner" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableLoyalty" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "enableQuickKeys" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableTwoFactor" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "establishedDate" TIMESTAMP(3),
ADD COLUMN     "expiryWarningDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "firstDayOfWeek" TEXT NOT NULL DEFAULT 'monday',
ADD COLUMN     "invoicePrefix" TEXT NOT NULL DEFAULT 'INV-',
ADD COLUMN     "invoiceStartNumber" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "language" TEXT NOT NULL DEFAULT 'roman_ur',
ADD COLUMN     "legalName" TEXT,
ADD COLUMN     "loyaltyPointsPerRupee" DOUBLE PRECISION NOT NULL DEFAULT 0.01,
ADD COLUMN     "loyaltyRedemptionRate" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "managerPin" TEXT,
ADD COLUMN     "maxDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "maxLoginAttempts" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "notifyDailySummary" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyLowStock" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyNewCustomer" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notifyNewSale" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notifyOutOfStock" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "openTime" TEXT,
ADD COLUMN     "printCopiesCount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "pushNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowBarcode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receiptShowCustomer" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowLogo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowQrCode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receiptShowTax" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptSize" TEXT NOT NULL DEFAULT 'THERMAL_58MM',
ADD COLUMN     "reorderPoint" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "requireCustomerForSale" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requirePinForDiscount" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requirePinForRefund" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "requirePinForVoid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "roundPriceTo" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "roundTotal" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "shopCity" TEXT,
ADD COLUMN     "shopPostalCode" TEXT,
ADD COLUMN     "shopProvince" TEXT,
ADD COLUMN     "shopWebsite" TEXT,
ADD COLUMN     "shopWhatsapp" TEXT,
ADD COLUMN     "showProductImages" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "smsNotifications" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stockMethod" TEXT NOT NULL DEFAULT 'AVERAGE',
ADD COLUMN     "taxInclusive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "taxLabel" TEXT NOT NULL DEFAULT 'GST',
ADD COLUMN     "theme" TEXT NOT NULL DEFAULT 'light',
ADD COLUMN     "timezone" TEXT NOT NULL DEFAULT 'Asia/Karachi',
ADD COLUMN     "trackExpiry" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "whatsappNotifications" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "workingDays" TEXT[] DEFAULT ARRAY['mon', 'tue', 'wed', 'thu', 'fri', 'sat']::TEXT[];
