// ═══════════════════════════════════════════════════════════════
// Industry themes for marketplace UI — mirrors the products list
// ═══════════════════════════════════════════════════════════════

export interface MarketplaceIndustryTheme {
  id: string;
  emoji: string;
  label: string;
  gradient: string;
  ribbon: string;
  accent: string;
  accentHex: string;
  accentBg: string;
  // Unit hints — for product cards
  unitLabels: { singular: string; plural: string };
  // Card badge text
  cardBadge?: string;
  // Show stock as
  stockDisplay: 'quantity' | 'sqft' | 'weight' | 'pieces' | 'menu' | 'service' | 'rooms';
  // Extra fields the seller cares about
  extraProductFields?: string[];
}

export const MARKETPLACE_INDUSTRY_THEMES: Record<string, MarketplaceIndustryTheme> = {
  carpet: {
    id: 'carpet',
    emoji: '🧶',
    label: 'Carpet',
    gradient: 'from-slate-950 via-emerald-900 to-emerald-700',
    ribbon: 'from-emerald-600 to-emerald-700',
    accent: 'emerald',
    accentHex: '#059669',
    accentBg: 'bg-emerald-50',
    unitLabels: { singular: 'sqft', plural: 'sqft' },
    cardBadge: 'Roll/Cut Piece',
    stockDisplay: 'sqft',
    extraProductFields: ['pileHeight', 'material', 'origin'],
  },
  mobile: {
    id: 'mobile',
    emoji: '📱',
    label: 'Mobile',
    gradient: 'from-slate-950 via-blue-900 to-indigo-700',
    ribbon: 'from-blue-600 to-indigo-700',
    accent: 'blue',
    accentHex: '#2563eb',
    accentBg: 'bg-blue-50',
    unitLabels: { singular: 'piece', plural: 'pieces' },
    cardBadge: 'IMEI Tracked',
    stockDisplay: 'pieces',
    extraProductFields: ['storage', 'ram', 'color', 'ptaStatus'],
  },
  retail: {
    id: 'retail',
    emoji: '🛒',
    label: 'Retail',
    gradient: 'from-slate-950 via-sky-900 to-cyan-700',
    ribbon: 'from-sky-600 to-cyan-700',
    accent: 'sky',
    accentHex: '#0ea5e9',
    accentBg: 'bg-sky-50',
    unitLabels: { singular: 'pc', plural: 'pcs' },
    stockDisplay: 'quantity',
  },
  restaurant: {
    id: 'restaurant',
    emoji: '🍽️',
    label: 'Restaurant',
    gradient: 'from-slate-950 via-orange-900 to-red-700',
    ribbon: 'from-orange-600 to-red-700',
    accent: 'orange',
    accentHex: '#ea580c',
    accentBg: 'bg-orange-50',
    unitLabels: { singular: 'plate', plural: 'plates' },
    cardBadge: 'Menu Item',
    stockDisplay: 'menu',
    extraProductFields: ['spiceLevel', 'dietaryTags', 'prepMinutes'],
  },
  pharmacy: {
    id: 'pharmacy',
    emoji: '💊',
    label: 'Pharmacy',
    gradient: 'from-slate-950 via-teal-900 to-emerald-700',
    ribbon: 'from-teal-600 to-emerald-700',
    accent: 'teal',
    accentHex: '#0d9488',
    accentBg: 'bg-teal-50',
    unitLabels: { singular: 'pack', plural: 'packs' },
    cardBadge: 'Rx / OTC',
    stockDisplay: 'quantity',
    extraProductFields: ['prescriptionRequired', 'expiryDate', 'batchNumber'],
  },
  bakery: {
    id: 'bakery',
    emoji: '🍰',
    label: 'Bakery',
    gradient: 'from-slate-950 via-pink-900 to-fuchsia-700',
    ribbon: 'from-pink-600 to-fuchsia-700',
    accent: 'pink',
    accentHex: '#ec4899',
    accentBg: 'bg-pink-50',
    unitLabels: { singular: 'piece', plural: 'pieces' },
    stockDisplay: 'quantity',
    extraProductFields: ['freshBaked', 'eggless', 'sizeOptions'],
  },
  garments: {
    id: 'garments',
    emoji: '👗',
    label: 'Garments',
    gradient: 'from-slate-950 via-rose-900 to-pink-700',
    ribbon: 'from-rose-600 to-pink-700',
    accent: 'rose',
    accentHex: '#e11d48',
    accentBg: 'bg-rose-50',
    unitLabels: { singular: 'piece', plural: 'pieces' },
    stockDisplay: 'quantity',
    extraProductFields: ['sizes', 'colors', 'fabric', 'season'],
  },
  jewelry: {
    id: 'jewelry',
    emoji: '💎',
    label: 'Jewelry',
    gradient: 'from-slate-950 via-amber-900 to-yellow-700',
    ribbon: 'from-amber-600 to-yellow-700',
    accent: 'amber',
    accentHex: '#d97706',
    accentBg: 'bg-amber-50',
    unitLabels: { singular: 'piece', plural: 'pieces' },
    cardBadge: 'Gold/Silver',
    stockDisplay: 'pieces',
    extraProductFields: ['metalType', 'purity', 'weight', 'stones'],
  },
  hardware: {
    id: 'hardware',
    emoji: '🔧',
    label: 'Hardware',
    gradient: 'from-slate-950 via-stone-800 to-zinc-700',
    ribbon: 'from-stone-700 to-zinc-800',
    accent: 'stone',
    accentHex: '#57534e',
    accentBg: 'bg-stone-50',
    unitLabels: { singular: 'pc', plural: 'pcs' },
    stockDisplay: 'quantity',
  },
  dairy: {
    id: 'dairy',
    emoji: '🥛',
    label: 'Dairy',
    gradient: 'from-slate-950 via-cyan-900 to-sky-700',
    ribbon: 'from-cyan-600 to-sky-700',
    accent: 'cyan',
    accentHex: '#0891b2',
    accentBg: 'bg-cyan-50',
    unitLabels: { singular: 'litre', plural: 'litres' },
    stockDisplay: 'quantity',
    extraProductFields: ['fatPercent', 'freshness'],
  },
  meat: {
    id: 'meat',
    emoji: '🥩',
    label: 'Meat',
    gradient: 'from-slate-950 via-red-900 to-rose-700',
    ribbon: 'from-red-700 to-rose-800',
    accent: 'red',
    accentHex: '#dc2626',
    accentBg: 'bg-red-50',
    unitLabels: { singular: 'kg', plural: 'kg' },
    cardBadge: 'Halal',
    stockDisplay: 'weight',
    extraProductFields: ['animalType', 'cutType', 'halalCertified'],
  },
  agri: {
    id: 'agri',
    emoji: '🌾',
    label: 'Agri',
    gradient: 'from-slate-950 via-lime-900 to-green-700',
    ribbon: 'from-lime-600 to-green-700',
    accent: 'lime',
    accentHex: '#65a30d',
    accentBg: 'bg-lime-50',
    unitLabels: { singular: 'kg', plural: 'kg' },
    stockDisplay: 'weight',
  },
  autoparts: {
    id: 'autoparts',
    emoji: '🔩',
    label: 'Auto Parts',
    gradient: 'from-slate-950 via-slate-800 to-neutral-700',
    ribbon: 'from-slate-700 to-neutral-800',
    accent: 'slate',
    accentHex: '#334155',
    accentBg: 'bg-slate-50',
    unitLabels: { singular: 'pc', plural: 'pcs' },
    stockDisplay: 'quantity',
    extraProductFields: ['vehicleFitment', 'partNumber', 'oem'],
  },
  bookstore: {
    id: 'bookstore',
    emoji: '📚',
    label: 'Bookstore',
    gradient: 'from-slate-950 via-indigo-900 to-violet-700',
    ribbon: 'from-indigo-600 to-violet-700',
    accent: 'indigo',
    accentHex: '#4f46e5',
    accentBg: 'bg-indigo-50',
    unitLabels: { singular: 'copy', plural: 'copies' },
    stockDisplay: 'quantity',
    extraProductFields: ['author', 'publisher', 'isbn'],
  },
  salon: {
    id: 'salon',
    emoji: '💇',
    label: 'Salon',
    gradient: 'from-slate-950 via-purple-900 to-fuchsia-700',
    ribbon: 'from-purple-600 to-fuchsia-700',
    accent: 'purple',
    accentHex: '#9333ea',
    accentBg: 'bg-purple-50',
    unitLabels: { singular: 'service', plural: 'services' },
    cardBadge: 'Service',
    stockDisplay: 'service',
    extraProductFields: ['durationMinutes', 'genderTarget'],
  },
  hotel: {
    id: 'hotel',
    emoji: '🏨',
    label: 'Hotel',
    gradient: 'from-slate-950 via-blue-900 to-cyan-700',
    ribbon: 'from-blue-700 to-cyan-700',
    accent: 'blue',
    accentHex: '#1d4ed8',
    accentBg: 'bg-blue-50',
    unitLabels: { singular: 'night', plural: 'nights' },
    cardBadge: 'Room',
    stockDisplay: 'rooms',
    extraProductFields: ['roomType', 'bedType', 'amenities'],
  },
  clinic: {
    id: 'clinic',
    emoji: '🩺',
    label: 'Clinic',
    gradient: 'from-slate-950 via-cyan-900 to-blue-700',
    ribbon: 'from-cyan-600 to-blue-700',
    accent: 'cyan',
    accentHex: '#06b6d4',
    accentBg: 'bg-cyan-50',
    unitLabels: { singular: 'session', plural: 'sessions' },
    stockDisplay: 'service',
  },
  gym: {
    id: 'gym',
    emoji: '💪',
    label: 'Gym',
    gradient: 'from-slate-950 via-red-900 to-orange-700',
    ribbon: 'from-red-700 to-orange-700',
    accent: 'red',
    accentHex: '#b91c1c',
    accentBg: 'bg-red-50',
    unitLabels: { singular: 'plan', plural: 'plans' },
    stockDisplay: 'service',
  },
  'services-biz': {
    id: 'services-biz',
    emoji: '🛠️',
    label: 'Services',
    gradient: 'from-slate-950 via-sky-900 to-blue-700',
    ribbon: 'from-sky-700 to-blue-700',
    accent: 'sky',
    accentHex: '#0369a1',
    accentBg: 'bg-sky-50',
    unitLabels: { singular: 'service', plural: 'services' },
    stockDisplay: 'service',
  },
  default: {
    id: 'default',
    emoji: '📦',
    label: 'Product',
    gradient: 'from-slate-950 via-slate-800 to-slate-700',
    ribbon: 'from-slate-700 to-slate-800',
    accent: 'slate',
    accentHex: '#475569',
    accentBg: 'bg-slate-50',
    unitLabels: { singular: 'unit', plural: 'units' },
    stockDisplay: 'quantity',
  },
};

export function getIndustryTheme(industryId?: string | null): MarketplaceIndustryTheme {
  if (!industryId) return MARKETPLACE_INDUSTRY_THEMES.default;
  return MARKETPLACE_INDUSTRY_THEMES[industryId] ?? MARKETPLACE_INDUSTRY_THEMES.default;
}
