import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { BookBinding, BookCategory, BookCondition } from '@prisma/client';
import { IsArray, IsBoolean, IsEnum, IsInt, IsNumber, IsOptional, IsString } from 'class-validator';

export class UpsertBookDto {
  @ApiProperty() @IsString() productId!: string;
  @ApiProperty() @IsString() title!: string;
  @ApiPropertyOptional() @IsOptional() @IsString() subtitle?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() originalTitle?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() isbn10?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() isbn13?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() publisherBookCode?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() barcode?: string;
  @ApiPropertyOptional({ enum: BookCategory }) @IsOptional() @IsEnum(BookCategory) category?: BookCategory;
  @ApiPropertyOptional() @IsOptional() @IsString() subCategory?: string;
  @ApiPropertyOptional({ enum: BookBinding }) @IsOptional() @IsEnum(BookBinding) binding?: BookBinding;
  @ApiPropertyOptional({ enum: BookCondition }) @IsOptional() @IsEnum(BookCondition) condition?: BookCondition;
  @ApiPropertyOptional() @IsOptional() @IsString() publisherId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() edition?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() editionNumber?: number;
  @ApiPropertyOptional() @IsOptional() @IsInt() publishYear?: number;
  @ApiPropertyOptional() @IsOptional() @IsInt() reprintYear?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() language?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() pageCount?: number;
  @ApiPropertyOptional() @IsOptional() @IsNumber() weightGrams?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() dimensions?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() paperQuality?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() description?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() tableOfContents?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() synopsis?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() isTextbook?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsString() grade?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() classLevel?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() subject?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() board?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() curriculum?: string;
  @ApiPropertyOptional() @IsOptional() @IsNumber() mrp?: number;
  @ApiPropertyOptional() @IsOptional() @IsNumber() discountPct?: number;
  @ApiPropertyOptional() @IsOptional() @IsInt() reorderLevel?: number;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() isBestSeller?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() isNewArrival?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() isFeatured?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() isAwardWinner?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsString() awardName?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() isRentable?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsNumber() rentalPricePerWeek?: number;
  @ApiPropertyOptional() @IsOptional() @IsNumber() rentalDeposit?: number;
  @ApiPropertyOptional({ type: [Object] }) @IsOptional() @IsArray() authors?: { authorId: string; role?: string; displayOrder?: number }[];
}
